version: '2'

services:
  bibliotekarz_nginx:
    container_name: bibliotekarz_nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html/
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network
  bibliotekarz_php:
    container_name: bibliotekarz_php
    build: './docker/php/'
    volumes:
      - ./:/var/www/html/
    networks:
      - code-network
  bibliotekarz_mysql:
    container_name: bibliotekarz_mysql
    image: mysql:5.7
    networks:
      - code-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bazka
      MYSQL_USER: user
      MYSQL_PASSWORD: user

  bibliotekarz_phpmyadmin:
    container_name: bibliotekarz_phpmyadmin
    image: phpmyadmin/phpmyadmin
    networks:
      - code-network
    depends_on:
      - bibliotekarz_mysql
    ports:
      - 8081:80
    environment:
      PMA_HOST: bibliotekarz_mysql
      PMA_USER: root
      PMA_PASSWORD: root
networks:
  code-network:
    driver: bridge