version: '2'

services:
  bibliotekarz_nginx:
    container_name: bibliotekarz_nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/code
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network
  bibliotekarz_php:
    container_name: bibliotekarz_php
    build: './docker/php/'
    volumes:
      - ./:/code
    networks:
      - code-network

networks:
  code-network:
    driver: bridge